SET(EVENTHUB_COMMON_FOUND "NO")

SET(EVENTHUB_COMMON_SEARCH_PATHS
	/usr/local/
        /sw/
	/usr/
)

FIND_PATH(EVENTHUB_COMMON_INCLUDE_DIR
	NAMES threadapi.h
	PATH_SUFFIXES /include/eventhubs
	PATHS ${EVENTHUB_COMMON_SEARCH_PATHS}
)

FIND_LIBRARY(EVENTHUB_COMMON_LIBRARY
	NAMES eventhub_common
	PATH_SUFFIXES /lib/
	PATHS ${EVENTHUB_COMMON_SEARCH_PATHS}
)

IF(EVENTHUB_COMMON_LIBRARY AND EVENTHUB_COMMON_INCLUDE_DIR)
  SET(EVENTHUB_COMMON_FOUND "YES")
ENDIF(EVENTHUB_COMMON_LIBRARY AND EVENTHUB_COMMON_INCLUDE_DIR)

IF(EVENTHUB_COMMON_LIBRARY)
	SET(CMAKE_REQUIRED_LIBRARIES ${EVENTHUB_COMMON_LIBRARY})
ENDIF(EVENTHUB_COMMON_LIBRARY)

IF(EVENTHUB_COMMON_FOUND)
  IF(NOT EVENTHUB_COMMON_FIND_QUIETLY)
    MESSAGE(STATUS "Found EVENTHUB_COMMON: ${EVENTHUB_COMMON_LIBRARY},${EVENTHUB_COMMON_INCLUDE_DIR}")
  ENDIF(NOT EVENTHUB_COMMON_FIND_QUIETLY)
ELSE(EVENTHUB_COMMON_FOUND)
#  IF(EVENTHUB_COMMON_FIND_REQUIRED)
#    MESSAGE(FATAL_ERROR "Could not find EVENTHUB_COMMON Library")
#  ENDIF(EVENTHUB_COMMON_FIND_REQUIRED)
ENDIF(EVENTHUB_COMMON_FOUND)