SET(EVENTHUB_CLIENT_FOUND "NO")

SET(EVENTHUB_CLIENT_SEARCH_PATHS
	/usr/local/
        /sw/
	/usr/
)

FIND_PATH(EVENTHUB_CLIENT_INCLUDE_DIR
	NAMES eventhubclient.h
	PATH_SUFFIXES /include/eventhubs
	PATHS ${EVENTHUB_CLIENT_SEARCH_PATHS}
)

FIND_LIBRARY(EVENTHUB_CLIENT_LIBRARY
	NAMES eventhub_client
	PATH_SUFFIXES /lib/
	PATHS ${EVENTHUB_CLIENT_SEARCH_PATHS}
)

IF(EVENTHUB_CLIENT_LIBRARY AND EVENTHUB_CLIENT_INCLUDE_DIR)
  SET(EVENTHUB_CLIENT_FOUND "YES")
ENDIF(EVENTHUB_CLIENT_LIBRARY AND EVENTHUB_CLIENT_INCLUDE_DIR)

IF(EVENTHUB_CLIENT_LIBRARY)
	SET(CMAKE_REQUIRED_LIBRARIES ${EVENTHUB_CLIENT_LIBRARY})
ENDIF(EVENTHUB_CLIENT_LIBRARY)

IF(EVENTHUB_CLIENT_FOUND)
  IF(NOT EVENTHUB_CLIENT_FIND_QUIETLY)
    MESSAGE(STATUS "Found EVENTHUB_CLIENT: ${EVENTHUB_CLIENT_LIBRARY},${EVENTHUB_CLIENT_INCLUDE_DIR}")
  ENDIF(NOT EVENTHUB_CLIENT_FIND_QUIETLY)
ELSE(EVENTHUB_CLIENT_FOUND)
#  IF(EVENTHUB_CLIENT_FIND_REQUIRED)
#    MESSAGE(FATAL_ERROR "Could not find EVENTHUB_CLIENT Library")
#  ENDIF(EVENTHUB_CLIENT_FIND_REQUIRED)
ENDIF(EVENTHUB_CLIENT_FOUND)